# Generated by Django 3.1.7 on 2021-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Phone_No', models.IntegerField()),
                ('Emailid', models.CharField(max_length=30)),
                ('Education', models.CharField(max_length=30)),
                ('Skills', models.CharField(max_length=30)),
                ('Languages', models.CharField(max_length=30)),
                ('Certificates', models.CharField(max_length=30)),
                ('Projects', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('Summary', models.CharField(max_length=30)),
            ],
        ),
    ]
